In [42]:
from utils.branch_bound import matrix_table, branch_bound_tree

ImportError: cannot import name 'matrix_table' from 'utils.branch_bound' (d:\VisualStudioCode\SBU-SPRING-2024\ESE556_VLSIAlgos\Project3-Two_Level_Logic_Synthesis\utils\branch_bound.py)

In [ ]:
from collections import defaultdict

In [ ]:
import numpy as np

In [ ]:
s = '11101010101'
array_of_integers = np.array(list(s), dtype=int)
print(array_of_integers)

[1 1 1 0 1 0 1 0 1 0 1]


In [ ]:
integers = [0, 1, 2, 3, 6, 7, 8, 9, 14, 15]
max_int = max(integers)
print(max_int)
max_bit = format(max_int, 'b')
print(max_bit)
print(len(max_bit))
bit_format = str(len(max_bit))+'b'
print(bit_format)
# Convert integers to binary representations
binary_representations = {integer: format(integer, bit_format).replace(' ', '0') for integer in integers}
print(binary_representations)


15
1111
4
4b
{0: '0000', 1: '0001', 2: '0010', 3: '0011', 6: '0110', 7: '0111', 8: '1000', 9: '1001', 14: '1110', 15: '1111'}


In [ ]:
from collections import defaultdict

In [ ]:
binary_lists = defaultdict(list)
for integer, bits_str in binary_representations.items():
    bits = []
    for byte in bits_str:
        binary_lists[integer].append(int(byte))
print(binary_lists)

defaultdict(<class 'list'>, {0: [0, 0, 0, 0], 1: [0, 0, 0, 1], 2: [0, 0, 1, 0], 3: [0, 0, 1, 1], 6: [0, 1, 1, 0], 7: [0, 1, 1, 1], 8: [1, 0, 0, 0], 9: [1, 0, 0, 1], 14: [1, 1, 1, 0], 15: [1, 1, 1, 1]})


In [ ]:
minterm_table = defaultdict(str)
group_table = defaultdict(list)
for minterm, bits in binary_lists.items():
    uninverted_bits_count = sum(bits)
    
    group_table[uninverted_bits_count].append((minterm,))
    for byte in bits:
        minterm_table[(minterm,)]+=str(byte)

In [ ]:
group_table

defaultdict(list,
            {0: [(0,)],
             1: [(1,), (2,), (8,)],
             2: [(3,), (6,), (9,)],
             3: [(7,), (14,)],
             4: [(15,)]})

In [ ]:
minterm_table

defaultdict(str,
            {(0,): '0000',
             (1,): '0001',
             (2,): '0010',
             (3,): '0011',
             (6,): '0110',
             (7,): '0111',
             (8,): '1000',
             (9,): '1001',
             (14,): '1110',
             (15,): '1111'})

In [ ]:
uninv_bits_counts = list(group_table.keys())
for idx in range(len(uninv_bits_counts)-1):
    current_group, next_group = uninv_bits_counts[idx], uninv_bits_counts[idx+1]
    print(current_group, next_group)

0 1
1 2
2 3
3 4


In [ ]:
print(group_table)

defaultdict(<class 'list'>, {0: [(0,)], 1: [(1,), (2,), (8,)], 2: [(3,), (6,), (9,)], 3: [(7,), (14,)], 4: [(15,)]})


In [ ]:
print(minterm_table)

defaultdict(<class 'str'>, {(0,): '0000', (1,): '0001', (2,): '0010', (3,): '0011', (6,): '0110', (7,): '0111', (8,): '1000', (9,): '1001', (14,): '1110', (15,): '1111'})


In [ ]:
group_table

defaultdict(list,
            {0: [(0,)],
             1: [(1,), (2,), (8,)],
             2: [(3,), (6,), (9,)],
             3: [(7,), (14,)],
             4: [(15,)]})

In [ ]:
group_table[1]

[(1,), (2,), (8,)]

In [ ]:
group_table[2]

[(3,), (6,), (9,)]

In [ ]:
# uninv_bits_counts = list(group_table.keys())
# next_group_table = defaultdict(list)
# absorbed_groups = {}
# for idx in range(len(uninv_bits_counts)-1):
#     current_group, next_group = uninv_bits_counts[idx], uninv_bits_counts[idx+1]
#     for current_minterms in group_table[current_group]:
#         for next_minterms in group_table[next_group]:
#             count = 0
#             variable = ''
#             current_bits = minterm_table[current_minterms]
#             next_bits = minterm_table[next_minterms]
#             for byte_idx in range(0,4):
#                 current_byte = current_bits[byte_idx]
#                 next_byte = next_bits[byte_idx]
#                 if current_byte == next_byte:
#                     if current_byte and next_byte:
#                         variable += '1'
#                     elif (not current_byte) and (not next_byte):
#                         variable += '0'
#                 # elif current_byte != next_byte: 
#                 else:
#                     variable += '-'
#                     count += 1
#             if count >= 3:
#                 continue
#             next_group_table[idx].append((current_minterms, next_minterms))
#             absorbed_groups[(current_minterms, next_minterms)] = variable
            
# print(absorbed_groups)


In [ ]:
group_table

defaultdict(list,
            {0: [(0,)],
             1: [(1,), (2,), (8,)],
             2: [(3,), (6,), (9,)],
             3: [(7,), (14,)],
             4: [(15,)]})

In [ ]:
def simplify_prime_implicants(group_table, minterm_table):
    uninv_bits_counts = list(group_table.keys())
    next_group_table = defaultdict(list)
    next_minterm_table = {}
    unique_bits = set()
    last_group_check = set(group for group_vals in group_table.values() for group in group_vals)
    for idx in range(len(uninv_bits_counts)-1):
        current_group, next_group = uninv_bits_counts[idx], uninv_bits_counts[idx+1]
        for current_minterms in group_table[current_group]:
            print("Current Minterm: ", current_minterms)
            for next_minterms in group_table[next_group]:
                print("Next Minterm: ", next_minterms)
                count = 0
                variable = ''
                current_bits = minterm_table[current_minterms]
                print("Current Bits", current_bits)
                next_bits = minterm_table[next_minterms]

                for byte_idx in range(0,4):
                    current_byte = current_bits[byte_idx]
                    next_byte = next_bits[byte_idx]
                    if current_byte == next_byte:
                        variable += current_bits[byte_idx]
                    else:
                        variable += '-'
                        count += 1

                if count == 1 and variable not in unique_bits:
                    next_group_table[idx].append((current_minterms+next_minterms))
                    next_minterm_table[current_minterms+next_minterms] = variable
                    unique_bits.add(variable)
                    print("Discard: ", current_minterms, next_minterms)
                    last_group_check.discard(current_minterms)
                    last_group_check.discard(next_minterms)
                    print("New group check: ", last_group_check)
    return next_group_table, next_minterm_table, last_group_check

In [ ]:
next_group_table, next_minterm_table, last_group_check = simplify_prime_implicants(group_table, minterm_table)

Current Minterm:  (0,)
Next Minterm:  (1,)
Current Bits 0000
Discard:  (0,) (1,)
New group check:  {(6,), (2,), (15,), (8,), (14,), (7,), (3,), (9,)}
Next Minterm:  (2,)
Current Bits 0000
Discard:  (0,) (2,)
New group check:  {(6,), (15,), (8,), (14,), (7,), (3,), (9,)}
Next Minterm:  (8,)
Current Bits 0000
Discard:  (0,) (8,)
New group check:  {(6,), (15,), (14,), (7,), (3,), (9,)}
Current Minterm:  (1,)
Next Minterm:  (3,)
Current Bits 0001
Discard:  (1,) (3,)
New group check:  {(6,), (15,), (14,), (7,), (9,)}
Next Minterm:  (6,)
Current Bits 0001
Next Minterm:  (9,)
Current Bits 0001
Discard:  (1,) (9,)
New group check:  {(6,), (15,), (14,), (7,)}
Current Minterm:  (2,)
Next Minterm:  (3,)
Current Bits 0010
Discard:  (2,) (3,)
New group check:  {(6,), (15,), (14,), (7,)}
Next Minterm:  (6,)
Current Bits 0010
Discard:  (2,) (6,)
New group check:  {(15,), (14,), (7,)}
Next Minterm:  (9,)
Current Bits 0010
Current Minterm:  (8,)
Next Minterm:  (3,)
Current Bits 1000
Next Minterm:  (6,)

In [ ]:
next_group_table

defaultdict(list,
            {0: [(0, 1), (0, 2), (0, 8)],
             1: [(1, 3), (1, 9), (2, 3), (2, 6), (8, 9)],
             2: [(3, 7), (6, 7), (6, 14)],
             3: [(7, 15), (14, 15)]})

In [ ]:
next_minterm_table

{(0, 1): '000-',
 (0, 2): '00-0',
 (0, 8): '-000',
 (1, 3): '00-1',
 (1, 9): '-001',
 (2, 3): '001-',
 (2, 6): '0-10',
 (8, 9): '100-',
 (3, 7): '0-11',
 (6, 7): '011-',
 (6, 14): '-110',
 (7, 15): '-111',
 (14, 15): '111-'}

In [ ]:
next_group_table2, next_minterm_table2, last_group_check2 = simplify_prime_implicants(next_group_table, next_minterm_table)

Current Minterm:  (0, 1)
Next Minterm:  (1, 3)
Current Bits 000-
Next Minterm:  (1, 9)
Current Bits 000-
Next Minterm:  (2, 3)
Current Bits 000-
Discard:  (0, 1) (2, 3)
New group check:  {(3, 7), (6, 14), (14, 15), (6, 7), (0, 2), (8, 9), (2, 6), (7, 15), (0, 8), (1, 3), (1, 9)}
Next Minterm:  (2, 6)
Current Bits 000-
Next Minterm:  (8, 9)
Current Bits 000-
Discard:  (0, 1) (8, 9)
New group check:  {(3, 7), (6, 14), (14, 15), (6, 7), (0, 2), (2, 6), (7, 15), (0, 8), (1, 3), (1, 9)}
Current Minterm:  (0, 2)
Next Minterm:  (1, 3)
Current Bits 00-0
Next Minterm:  (1, 9)
Current Bits 00-0
Next Minterm:  (2, 3)
Current Bits 00-0
Next Minterm:  (2, 6)
Current Bits 00-0
Next Minterm:  (8, 9)
Current Bits 00-0
Current Minterm:  (0, 8)
Next Minterm:  (1, 3)
Current Bits -000
Next Minterm:  (1, 9)
Current Bits -000
Next Minterm:  (2, 3)
Current Bits -000
Next Minterm:  (2, 6)
Current Bits -000
Next Minterm:  (8, 9)
Current Bits -000
Current Minterm:  (1, 3)
Next Minterm:  (3, 7)
Current Bits 00-

In [ ]:
next_group_table2

defaultdict(list,
            {0: [(0, 1, 2, 3), (0, 1, 8, 9)],
             1: [(2, 3, 6, 7)],
             2: [(6, 7, 14, 15)]})

In [ ]:
next_minterm_table2

{(0, 1, 2, 3): '00--',
 (0, 1, 8, 9): '-00-',
 (2, 3, 6, 7): '0-1-',
 (6, 7, 14, 15): '-11-'}

In [43]:
test = {(0, 1, 2, 3),
 (0, 1, 8, 9),
 (2, 3, 6, 7),
 (6, 7, 14, 15),
 (6, 7, 14, 15, 2, 3, 6, 7),
 (12, 23, 124, 123, 123, 343, 63, 72),
 }
sorted_minterms = sorted(test, key=lambda x: (len(x), x))
sorted_minterms

[(0, 1, 2, 3),
 (0, 1, 8, 9),
 (2, 3, 6, 7),
 (6, 7, 14, 15),
 (6, 7, 14, 15, 2, 3, 6, 7),
 (12, 23, 124, 123, 123, 343, 63, 72)]

In [ ]:
max_bit = format(max_int, 'b')
most_significant_bit = len(max_bit)
minterm_matrix = np.zeros((most_significant_bit,len(integers)), dtype='int')
print(minterm_matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
integers.index(7)

5

In [ ]:
for idx, minterm in enumerate(next_minterm_table2.keys()):
    row = minterm_matrix[idx, :]
    for bit in minterm:
        row_idx = integers.index(bit)
        row[row_idx] = 1
    

In [ ]:
integers

[0, 1, 2, 3, 6, 7, 8, 9, 14, 15]

In [ ]:
next_minterm_table2.keys()

dict_keys([(0, 1, 2, 3), (0, 1, 8, 9), (2, 3, 6, 7), (6, 7, 14, 15)])

In [ ]:
minterm_matrix

array([[1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 1, 1]])

In [ ]:
col_sums = np.sum(minterm_matrix, axis = 0)
min_col_sums = min(col_sums)
print(min_col_sums)
indicies = np.where(col_sums == min_col_sums)[0]
print(indicies)

1
[6 7 8 9]


In [ ]:
next_matrix = np.delete(minterm_matrix, indicies, axis = 1)
print(next_matrix)

[[1 1 1 1 0 0]
 [1 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 0 0 0 1 1]]


In [ ]:
integers

[0, 1, 2, 3, 6, 7, 8, 9, 14, 15]

In [ ]:
next_prime_implicants = np.delete(integers, indicies, axis = 0)
print(next_prime_implicants)

[0 1 2 3 6 7]


10

In [ ]:
test = minterm_matrix[: , -1]
print(test)
idx = np.where(test == 1)[0][0]
print(idx)

[0 0 0 1]
3


In [ ]:
next_group_table3, next_minterm_table3 = simplify_prime_implicants(next_group_table2, next_minterm_table2)

In [ ]:
next_group_table3

defaultdict(list, {})

In [ ]:
next_minterm_table3

{}

In [ ]:
unique_check = set()
for minterms in next_minterm_table2.keys():
    for group in minterms:
        if group not in unique_check:
            unique_check.add(group)
        else:
            unique_check.remove(group)
print(unique_check)

{8, 9, 14, 15}


In [ ]:
keys_unique_groups = []
vals_unique_groups = []
for key in next_minterm_table2:
    if any(group in unique_check for group in key):
        keys_unique_groups.append(key)
        vals_unique_groups.append(next_minterm_table2[key])
print(keys_unique_groups)
print(vals_unique_groups)

[(0, 1, 8, 9), (6, 7, 14, 15)]
['-00-', '-11-']


In [ ]:
results = []
for minterms, bits in next_minterm_table2.items():
    final_result = ''
    if minterms not in keys_unique_groups:
        for unique_key in keys_unique_groups:
            final_result += next_minterm_table2[unique_key] + '+'
        final_result += bits
        results.append(final_result)

In [ ]:
print(results)

['-00-+-11-+00--', '-00-+-11-+0-1-']
