In [1]:
from utils.branch_bound import minterm_matrix, branch_bound_tree
from collections import defaultdict
import numpy as np

In [2]:
pi_input = [1,3,4,5,6,7,10,11,12,13,14,15,18,19,20,21,22,23,26,27]

In [3]:
# pi_input = [0, 1, 2, 3, 6, 7, 8, 9, 14, 15]

In [4]:
bbt = branch_bound_tree(pi_input)

{1: '00001', 3: '00011', 4: '00100', 5: '00101', 6: '00110', 7: '00111', 10: '01010', 11: '01011', 12: '01100', 13: '01101', 14: '01110', 15: '01111', 18: '10010', 19: '10011', 20: '10100', 21: '10101', 22: '10110', 23: '10111', 26: '11010', 27: '11011'}
leftover_minterms:  {(10, 11, 14, 15), (10, 11, 26, 27), (1, 3, 5, 7), (3, 11, 19, 27), (3, 7, 19, 23), (18, 19, 22, 23), (18, 19, 26, 27), (3, 7, 11, 15)}
Row Axis:  [((1, 3, 5, 7), '00--1'), ((3, 7, 11, 15), '0--11'), ((3, 7, 19, 23), '-0-11'), ((3, 11, 19, 27), '--011'), ((10, 11, 14, 15), '01-1-'), ((10, 11, 26, 27), '-101-'), ((18, 19, 22, 23), '10-1-'), ((18, 19, 26, 27), '1-01-'), ((4, 5, 6, 7, 12, 13, 14, 15), '0-1--'), ((4, 5, 6, 7, 20, 21, 22, 23), '-01--')]
Column Axis:  [1, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 18, 19, 20, 21, 22, 23, 26, 27]
[[1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1]
 [0 0 0 0 0