In [1]:
from utils.QMcC import QMcC_iter, prime_implicant
from utils.branch_and_bound import minterm_matrix, BB_tree
from collections import defaultdict
import numpy as np

In [2]:
# pi_input = [1,3,4,5,6,7,10,11,12,13,14,15,18,19,20,21,22,23,26,27]
# pi_input = [0, 1, 2, 3, 6, 7, 8, 9, 14, 15]
pi_input = [0, 1, 5, 6, 7] 

In [3]:
QMC = QMcC_iter(pi_input)

In [4]:
pi = QMC.final_pi
print(pi.pi_table)

defaultdict(<function QMcC_iter.simplify_prime_implicants.<locals>.<lambda> at 0x00000236136250D0>, {0: defaultdict(<class 'str'>, {(0, 1): '00-'}), 1: defaultdict(<class 'str'>, {(1, 5): '-01'}), 2: defaultdict(<class 'str'>, {(5, 7): '1-1', (6, 7): '11-'})})


In [5]:
BB = BB_tree(pi, pi_input)

Row Axis:  [((0, 1), '00-'), ((1, 5), '-01'), ((5, 7), '1-1'), ((6, 7), '11-')]
Column Axis:  [0, 1, 5, 6, 7]
[[1 1 0 0 0]
 [0 1 1 0 0]
 [0 0 1 0 1]
 [0 0 0 1 1]]
[[1]
 [1]]
cols zi:  [inf]
Row Ones:  [0]
Row Ones:  [0]
PI INDEX:  1
CURRENT_MATRIX: 
Solution Found!
Solution Found!
FINAL EQUATION:  [((6, 7), '11-'), ((0, 1), '00-'), ((1, 5), '-01')]
Branch and Bound Algorithm Complete!
