In [1]:
from utils.QMcC import QMcC_iter, prime_implicant
from utils.branch_and_bound import minterm_matrix, BB_tree
from collections import defaultdict
import numpy as np

In [2]:
pi_input = [1,3,4,5,6,7,10,11,12,13,14,15,18,19,20,21,22,23,26,27]
#pi_input = [0, 1, 2, 3, 6, 7, 8, 9, 14, 15]

In [3]:
QMC = QMcC_iter(pi_input)

In [4]:
pi = QMC.final_pi
print(pi.pi_table)

defaultdict(<function QMcC_iter.simplify_prime_implicants.<locals>.<lambda> at 0x0000023933FA2820>, {0: defaultdict(<class 'str'>, {(4, 5, 6, 7, 12, 13, 14, 15): '0-1--', (4, 5, 6, 7, 20, 21, 22, 23): '-01--'})})


In [5]:
BB = BB_tree(pi, pi_input)

leftover_minterms:  {(10, 11, 14, 15), (10, 11, 26, 27), (1, 3, 5, 7), (3, 11, 19, 27), (3, 7, 19, 23), (18, 19, 22, 23), (18, 19, 26, 27), (3, 7, 11, 15)}
Row Axis:  [((1, 3, 5, 7), '00--1'), ((3, 7, 11, 15), '0--11'), ((3, 7, 19, 23), '-0-11'), ((3, 11, 19, 27), '--011'), ((10, 11, 14, 15), '01-1-'), ((10, 11, 26, 27), '-101-'), ((18, 19, 22, 23), '10-1-'), ((18, 19, 26, 27), '1-01-'), ((4, 5, 6, 7, 12, 13, 14, 15), '0-1--'), ((4, 5, 6, 7, 20, 21, 22, 23), '-01--')]
Column Axis:  [1, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 18, 19, 20, 21, 22, 23, 26, 27]
[[1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0]]
Remove 

In [ ]:
matrix = np.array([
    [1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1],
    [0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0]
])

In [ ]:
matrix[0, :]

In [ ]:
def MiS_quick(M):
    # Convert M to a numpy array if it's not already
    if not isinstance(M, np.ndarray):
        M = np.array(M)
    
    MiS = set()
    cost = 0
    unit_cost = 1  # Cost of including each column in the set
    
    # Continue while M is not empty and there are columns left
    while M.size > 0 and M.shape[1] > 0:
        # Find the column with the least number of 1's (shortest column)
        column_sums = np.sum(M, axis=0)
        if np.all(column_sums == 0):
            break  # Exit if there are no more 1's in any column

        min_ones_index = np.argmin(column_sums)

        # Add index to MiS and update cost
        MiS.add(min_ones_index + 1)  # Adding 1 for human-readable indexing
        cost += unit_cost
        
        # Find all rows where the chosen column has 1's
        rows_with_ones = M[:, min_ones_index] == 1
        
        # Find all columns that have 1's in the same rows as the chosen column
        columns_to_delete = np.any(M[rows_with_ones], axis=0)

        # Delete these columns from M using np.delete
        indices_to_delete = np.where(columns_to_delete)[0]  # Get the actual indices to delete
        M = np.delete(M, indices_to_delete, axis=1)
    
    return cost  # Return the total cost of the selected columns