In [1]:
import numpy as np

In [2]:
integers = [0, 1, 2, 3, 6, 7, 8, 9, 14, 15]
max_int = max(integers)
print(max_int)
max_bit = format(max_int, 'b')
print(max_bit)
print(len(max_bit))
bit_format = str(len(max_bit))+'b'
print(bit_format)

15
1111
4
4b


In [1]:
test = (1,2,3,4,5)

: 

In [8]:
minterm_matrix = np.zeros((len(max_bit), len(integers)), dtype='int')
print(minterm_matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [9]:
minterm_matrix[:, 0]

array([0, 0, 0, 0])

In [10]:
for idx, integer in enumerate(integers):
    minterm = format(integer, bit_format).replace(' ', '0')
    minterm_array = np.array([int(char) for char in minterm])
    minterm_matrix[:, idx] = minterm_array
print(minterm_matrix)

[[0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 0 0 1 1]
 [0 0 1 1 1 1 0 0 1 1]
 [0 1 0 1 0 1 0 1 0 1]]


In [1]:
minterm_matrix[:,1]

NameError: name 'minterm_matrix' is not defined

In [18]:
col4  = minterm_matrix[:, 4]
print(col4)
indicies = np.where(col4 == 1)[0]
print(set(indicies))

[0 1 1 0]
{1, 2}


In [12]:
from collections import defaultdict
test = defaultdict(lambda: defaultdict(str))


In [13]:
test[0]['a']+= '1'
test[0]['a']+= '1'
test[0]['b']+= '0'
test[0]['a']+= '1'
test[1]['a']+= '1'

In [14]:
test

defaultdict(<function __main__.<lambda>()>,
            {0: defaultdict(str, {'a': '111', 'b': '0'}),
             1: defaultdict(str, {'a': '1'})})