In [1]:
import numpy as np

In [7]:
import numpy as np

def split_logic_matrix(logic_equation, matrix, var_index):
    # Initialize the new equations and matrices
    S0_equation = []
    S1_equation = []
    S0_rows = []
    S1_rows = []

    for minterms, pattern in logic_equation:
        if pattern[var_index] == '0':
            S0_equation.append((minterms, pattern))
            S0_rows.extend([m - 1 for m in minterms])  # Adjusting indices for 0-based indexing
        elif pattern[var_index] == '1':
            S1_equation.append((minterms, pattern))
            S1_rows.extend([m - 1 for m in minterms])  # Adjusting indices for 0-based indexing

    # Convert to unique numpy arrays
    S0_rows = np.unique(S0_rows)
    S1_rows = np.unique(S1_rows)

    # Filter out-of-bound indices
    S0_rows = S0_rows[S0_rows < matrix.shape[0]]
    S1_rows = S1_rows[S1_rows < matrix.shape[0]]

    # Generate matrices
    S0_matrix = matrix[S0_rows] if S0_rows.size > 0 else np.array([], dtype=matrix.dtype)
    S1_matrix = matrix[S1_rows] if S1_rows.size > 0 else np.array([], dtype=matrix.dtype)

    return S0_equation, S0_matrix, S1_equation, S1_matrix

# Example usage
matrix = np.array([
    [0, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0],
    [0, 1, 0, 1, 0, 1],
    [1, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 1, 1],
    [0, 0, 1, 1, 0, 0],
    [0, 0, 1, 1, 1, 1]
])
next_equation = [
    ((1, 3, 5, 7), '00--1'),
    ((4, 5, 6, 7, 12, 13, 14, 15), '0-1--'),
    ((4, 5, 6, 7, 20, 21, 22, 23), '-01--')
]
chosen_var_index = 2  # Let's say we are choosing the third variable ('c')

S0_eq, S0_mat, S1_eq, S1_mat = split_logic_matrix(next_equation, matrix, chosen_var_index)
print("S0 Equation:", S0_eq)
print("S0 Matrix:\n", S0_mat)
print("S1 Equation:", S1_eq)
print("S1 Matrix:\n", S1_mat)

S0 Equation: []
S0 Matrix:
 []
S1 Equation: [((4, 5, 6, 7, 12, 13, 14, 15), '0-1--'), ((4, 5, 6, 7, 20, 21, 22, 23), '-01--')]
S1 Matrix:
 [[1 1 0 0 0 0]
 [1 1 0 0 1 1]
 [0 0 1 1 0 0]
 [0 0 1 1 1 1]]


In [ ]:
def row_dominance(matrix, row_indices):
    pass

In [ ]:
def col_dominance(matrix, col_inidices):
    pass

In [19]:
def MiS_quick(matrix:np.array):
    MiS = set()
    matrix = matrix.copy()
    col_axis = np.arange(matrix.shape[1])
    while matrix.size > 0 and matrix.shape[1] > 0:
        print(matrix)
        column_sums = np.sum(matrix, axis = 0)
        min_sum = min(column_sums)
        min_column_indicies = np.where(column_sums == min_sum)[0]
        
        best_columns = []
        for col_idx in min_column_indicies:
            delete_cols = {col_idx}
            row_indicies = np.where(matrix[: , col_idx] == 1)[0]
            for row_idx in row_indicies:
                row = matrix[row_idx, :]
                col_indicies = np.where(row == 1)[0]
                delete_cols.update(set(col_indicies))
            cols_to_delete = list(delete_cols)
            col_score = np.sum(matrix[:, cols_to_delete])
            best_columns.append((col_idx, cols_to_delete, col_score))

        selected_column = min(best_columns, key=lambda x: x[2])
        selected_column_idx, selected_column_to_delete,_  = selected_column
        MiS.add(col_axis[selected_column_idx])
        matrix = np.delete(matrix, selected_column_to_delete, axis = 1)
        col_axis = np.delete(col_axis, selected_column_to_delete)
    return MiS

In [20]:
matrix = np.array([
    [1,1,0,0,0,0,1],
    [0,1,1,0,0,1,0],
    [0,0,1,0,1,0,1],
    [0,1,0,1,1,0,0],
    [1,0,0,1,0,0,0],
    [0,0,0,1,0,1,0]],
)
res = MiS_quick(matrix)
print(res)

[[1 1 0 0 0 0 1]
 [0 1 1 0 0 1 0]
 [0 0 1 0 1 0 1]
 [0 1 0 1 1 0 0]
 [1 0 0 1 0 0 0]
 [0 0 0 1 0 1 0]]
[[0 0 0]
 [1 0 1]
 [1 1 0]
 [0 1 0]
 [0 0 0]
 [0 0 1]]
[[0]
 [1]
 [0]
 [0]
 [0]
 [1]]
{0, 4, 5}


In [20]:
test = np.array(
        [
        ,
        [1,1,0,1,0,0],
        [0,1,1,0,0,0],
        [0,0,0,1,1,1],
        [0,0,1,1,0,0],
        [0,1,0,0,0,1],
        [1,0,1,0,0,0]
        ]
        )
res = MiS_quick(test)
print(res)

[[1 0 0 0 1 0]
 [1 1 0 1 0 0]
 [0 1 1 0 0 0]
 [0 0 0 1 1 1]
 [0 0 1 1 0 0]
 [0 1 0 0 0 1]
 [1 0 1 0 0 0]]
{4, 5}
set()


In [19]:
test = np.array(
        [
        [1,0,1,0,1,0],
        [1,0,0,1,0,1],
        [0,1,1,0,0,1],
        [0,1,0,1,1,0]
        ]
        )
res = MiS_quick(test)
print(res)

[[1 0 1 0 1 0]
 [1 0 0 1 0 1]
 [0 1 1 0 0 1]
 [0 1 0 1 1 0]]
{0, 1, 2, 3, 4, 5}
set()


In [6]:
test.shape[1]

6

In [4]:
integers = [0, 1, 2, 3, 6, 7, 8, 9, 14, 15]
max_int = max(integers)
print(max_int)
max_bit = format(max_int, 'b')
print(max_bit)
print(len(max_bit))
bit_format = str(len(max_bit))+'b'
print(bit_format)

15
1111
4
4b


In [3]:
test = (1,2,3,4,5)
print(test)

(1, 2, 3, 4, 5)


In [5]:
tuple(i for i in integers)


(0, 1, 2, 3, 6, 7, 8, 9, 14, 15)

In [8]:
minterm_matrix = np.zeros((len(max_bit), len(integers)), dtype='int')
print(minterm_matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
matrix = np.array([
    [1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1],
    [0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0]
])


In [9]:
minterm_matrix[:, 0]

array([0, 0, 0, 0])

In [10]:
for idx, integer in enumerate(integers):
    minterm = format(integer, bit_format).replace(' ', '0')
    minterm_array = np.array([int(char) for char in minterm])
    minterm_matrix[:, idx] = minterm_array
print(minterm_matrix)

[[0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 0 0 1 1]
 [0 0 1 1 1 1 0 0 1 1]
 [0 1 0 1 0 1 0 1 0 1]]


In [1]:
minterm_matrix[:,1]

NameError: name 'minterm_matrix' is not defined

In [18]:
col4  = minterm_matrix[:, 4]
print(col4)
indicies = np.where(col4 == 1)[0]
print(set(indicies))

[0 1 1 0]
{1, 2}


In [12]:
from collections import defaultdict
test = defaultdict(lambda: defaultdict(str))


In [13]:
test[0]['a']+= '1'
test[0]['a']+= '1'
test[0]['b']+= '0'
test[0]['a']+= '1'
test[1]['a']+= '1'

In [14]:
test

defaultdict(<function __main__.<lambda>()>,
            {0: defaultdict(str, {'a': '111', 'b': '0'}),
             1: defaultdict(str, {'a': '1'})})